language: node_js
node_js:
  - 12

install:
  - yarn

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  on:
    branch: master
  local_dir: frontend/dist/
  verbose: true
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: false
