language: node_js
deploy:
  - on: master
    provider: heroku
    app: wundershoppinglist
    api_key:
      secure: Cybd7fnkvQp46pPJRuNsA0hSMYyF4KJTZxmdTm9cah/qR+cRUVKHdROld1zNESxSQsHtrdkU6/47hkf16Kdn3kNUXBYpnpZPG0PyD0ggRweuEIUu20jSxW6BCOy7YC1AVN02VOiqkJkRkF0i2Iy9IXGO6GaM5EAeTUrmJdbSD2SwxxEPN5j6y5E6/TlB3Dvj6IVsTa/Y771n2B6ZT5xe4d/RBi1sGS8HCSarLwetVKtwBbCdVcvhakYHFOl5v+s6uOqTcy3Bcobcrb291mLvNCBe/e/SrjdTQx/brtwqsaMIBCJxWZk+TgAbF3KFM5M04uZp3SzD2WuRY7m2Zcs13g7oHp7vdvlkyZJTERWn3OUkqeQE3sSkoTkgS/4dw4qrdomRgG4CY5RkYVONklhq0yd2uPLaPx2cKEFezI9rzeJgzOae7q4/RxoT4i0+kXVW6saL1Ysy/kQNPIejc8UWonbo+f5ZYLyhjghtBg5wNhTWiQ5dFGD8D35/ZmQeiyp12Cah6Vp7fuBSrqCUwoAgF4J3sq7stoZr5rTgQmzevIMF48gfrm3F0yYBQDP7JPL23XnVkFFQtS0Zy1afZq7yTJftnkCO4QbTm3lr6rzBfYYRF8+6nUhJ6fVVbcmTXn6mczhGaHfC6CN4Wyc1iWO2L0/n7kOeru3eLaGRaTlQtjY=
